using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Paragraphs : MonoBehaviour
{
    public string[] paragraph = {"\"Hey honey! How was your day?\"\n\"Alright but I'm starving. What are we having for dinner?\"\n\"I don't know. Can we get delivery? I don't think I can cook today.\"\n\"Sure. It's been a long day for me too. _ _\"",
        "\"How did your date with John go last night?\"\n\"Ok I guess. I liked him a lot but honestly he chewed with his mouth open the whole dinner and it was _ _ _. I'm not sure if we'll go out again.\"",
        "\"What season of Is It Cake? are you on? You've been watching that show all day. You are such a _ _.\"",
        "\"I want to introduce you to my friend Amy. She went to law school like you.\"\n\"Hi, _ _. I'm Enrique.\"",
        "\"Do you want to hang out tonight?\"\n\"Yeah I can but is it ok if we just _? I don't have a lot of energy.\"",
        "\"I went to the bar, but it was _ so I decided to leave.\"",
        "\"_ politics have really changed the way the way people talk there.\"",
        "\"I was the only one in my math class to get an A on the final.\"\n\"Girl _.\"",
        "\"Did you see me backflip?\"\n\"Yeah dude that was _.\"",
        "\"I'm gonna _ _ _ after this game, I have a test on Friday.\"",
        "\"Anyone wanna go see a movie this weekend?\"\n\"_ _ as long as you pay.\"",
        "\"_ about the party, it got canceled due to the bad weather.\"",
        "\"Dude your car is _, I wish I had a car like that.\"",
        "\"Don’t worry, you're the best player out there. You have this _ _ _.\"",
        "\"I never see Abigal eat meat, is she a vegetarian?\"\n\"Nah she does, _ _ _ _ _.\"",
        "\"Are you still coming over Tuesday?\"\n\"_ _.\"",
        "\"I heard that Sam never does her homework.\"\n\"_ _ _ _, she's the smartest kid in our class.\"",
        "\"It was nice seeing you this weekend, we should really _ _ _.\"",
        "\"They got back together?_ _ _ right now.\"",
        "\"Sorry I was late, I lost track of time.\"\n\"It's _ _, I was a little late too.\"",
        "\"I really hope we can hang out tonight, if you can't make it it's _ _ _ though.\"",
        "\"I'll get it done by the deadline, _ _.\"",
        "\"He didn’t have to _ me _ like that with that guitar solo.\"",
        "\"He was always here to _ _ _ me when no one else would.\"",
        "\"I _ _ _ on you, you're so cute.\"",
        "\"My dream is to be a _ worker in some high-end company.\"",
        "\"I wish us _ workers had it easier.\"",
        "\"I didn’t do anything wrong, she's just being _ because of what I said yesterday.\"",
        "\"He was _ cheating on her.\"",
        "\"I love the new dress, you look like the _.\"",
        "\"She was being super _, I could tell she was hiding something.\"",
        "\"What a _ dad joke.\"",
        "\"Aw that’s a _, I'm sorry he couldn’t make it to your party.\"",
        "\"I'm _ _ a drink right about now.\"",
        "\"_ new car!.\"",
        "\"I'm not gonna _ _ until he starts using his manners.\"",
        "\"Would you be _ _ if we came over today.\"",
        "\"I wanna _ _ this weekend, are you avaliable?\"",
        "\"Dude that rollecoaster was so scary, when it when upside-down, I was _ _ _.\"",
        "\"I'm happy you got an A on the math test, but you don’t have to _ _ _ _ _.\"",
        "\"Is there any chance I can make it to school on time today.\"\n\"It's way too late now, _ _ _ _.\"",
        "\"I can't wait for your party this summer, we're going to _ _ _.\"",
        "\"Would you like to grab lunch with me this weekend.\"\n\"_ _, what time?\"",
        "\"_ _, I have been ever since my pet fish died.\"",
        "\"Don’t listen to him, hes a scammer, he likes to _ _ people for fun.\"",
        "\"It's time to go.\"\n\"Can I _ _.\"",
        "\"You always _ _ to her, what about me?\"",
        "\"She wanted the last slice, but I already _ _ _ it.\"",
        "\"He's _ _, its his first day on the job.\"",
        "\"Everytime she messes up, she tries to _ _ _ to me, I'm sick of it.\"",
        "\"Let's _ _ for dinner tonight.\"",
        "\"It's time to _ _ _, does anyone else want to come?\"",
        "\"Can we _ _ the party? I still have plans tonight.\"",
        "\"Are you sure you can handle this?\"\n\"_ _ _ _? I do it all the time.\"",
        "\"_ _ _ there's no way the test is tomorrow\"",
        "\"I need to _ _ on our plans, something came up.\"",
        "\"Can I tell you something?\"\n\"Sure, I'm _ _.\"",
        "\"I pulled an _ to finish her favorite show.\"",
        "\"She looks so pretty, she definitely had a _ _.\"",
        "\"Whenever he starts talking, I just _ _ what he has to say.\"",
        "\"I'm gonna _ this test.\"",
        "\"You're going to _ this job interview, I promise.\"",
        "\"He's always trying to _ _ me, I don’t know why.\"",
        "\"I _ _ constantly, I can't believe they haven't fired me yet.\"",
        "\"You look exhuasted, we have to get _ _ for this concert tonight.\"",
        "\"I just found out what happened to Abby.\"\n\"Really?_ _ _ she won't tell me.\"",
        "\"Did you _ just do that?\"",
        "\"I _ _ with her, she was talking about me behind my back.\"",
        "\"I want to go fishing this weekend, _ _ _\"",
        "\"_ _ _ _ skydive with me? It could be a lot of fun.\"",
        "\"I'm _ _ leave the house, Ive been inside all day.\"",
        "\"Don’t give her any chocolate, last time I did, she threw a _ _ when she ran out.\"",
        "\"I'm running short on _, could you pay instead?\"",
        "\"Time for work, hopefully I'll make more _ than last week.\"",
        "\"I'm so tired, as soon as I get home, I'm gonna _.\"",
        "\"_ _, things could be worse after all.\"",
        "\"I'm gonna _ tonight with her, I know it. She really likes me.\"",
        "\"There's only two more assignments left, as long as I can _ these, my grade will be fine.\"",
        "\"I'm sorry to _ on you but I won't be able to make it to the BBQ.\"",
        "\"She's so mean, we should _ her for somebody else.\"",
        "\"I _ my mom's favorite vase.\"",
        "\"I heard he got _ by the police.\"",
        "\"Don’t worry, I'll be done _ _ _.\"",
        "\"I gave out _ mugs to promote my buisness.\"",
        "\"_ _ I didn’t mean to do that.\"",
        "\"_ _ I mess up sometimes too.\"",
        "\"_ _ _, I grew up with anxiety too.\"",
        "\"I wish the weather was better.\"\n\"_ _.\"",
        "\"I wish I could hang out but my parents are too strict.\"\n\"_ _ _, so are mine.\"",
        "\"Did you see him score that goal? That was _.\"",
        "\"Dude she's like supermodel _.\"",
        "\"He kept using these really _ pickup lines, but I thought they were cute.\"",
        "\"She keeps acting strange, I don’t know why she's being so _.\"",
        "\"He cheated on you, you need to _ him.\"",
        "\"I want to _ _ with her, she doesn’t like pizza.\"",
        "\"Name one party you haven't seen her at, she's the biggest _ _ at our school.\"",
        "\"Dude I swear hes a math _, I've never seen someone solve problems that fast before.\"",
        "\"Go ask her out, don’t be a _.\"",
        "\"Dude that _ is so hot.\"",
        "\"Who wants to go to a concert this weekend.\"\n\"_ _ as long as I can bring my friend.\"",
        "\"Your party was a _! Everyone had so much fun.\"",
        "\"I'm totally gonna _ _ this weekend and eat whatever I want, I'm under so much stress.\"",
        "\"She's so rich and _.\"",
        "\"_ _ dude, fighting wont solve anything.\"",
        "\"I didn’t mean to _ _ _ like that, it was an accident.\""};

    public int[][] answers = new int[][] { new int[] {0, 1, 4}, 
        new int[] {3, 1, 2}};

    public string[] paragraphY = {"\"What is that music?\"\n\"Oh, it's something that my mom bought me. Just checking it out.\"\n\"_\"",
        "\"You can't do her laundry for her. She's not even your girlfriend. You're being such a _.\"",
        "\"Dude I had so much fun last night, that party was _!\"",
        "\"This blunt got me _.\"",
        "\"I got to start hitting the gym, I want to be super _.\"",
        "\"I just got back from the mall, rate the new _.\"",
        "\"I'm _ hit the gym, you tryna come?\"",
        "\"Wanna hang out this weekend?\"\n\"_.\"",
        "\"Ive never seen a car like that before, that’s _.\"",
        "\"I _ wanna play a game right now.\"",
        "\"Sorry I couldn’t make it this weekend, my mom is sick.\"\n\"You're all _, family comes first.\"",
        "\"I'm _, I wouldve never expected her to do that.\"",
        "\"He keeps acting _, I know he's up to something.\"",
        "\"Check out the new _.\"",
        "\"I finally finished my hair and make up, I look so _ _.\"",
        "\"After he cheated, I had to _ him on everything.\"",
        "\"You still down to hang out?\"\n\"_ girl you already know it.\"",
        "\"You have to be joking.\"\n\"_ _ it's true.\"",
        "\"That dance move was _ _, you looked just like a professional.\"",
        "\"You're _ weird for what you just said.\"",
        "\"That’s _ funny, how did that happen?.\"",
        "\"This album _, it's my new favorite.\"",
        "\"Everything at this resturant is _, especially the lasagna.\"",
        "\"You have so many _.\"",
        "\"I cant believe that drink is her favorite, It's so _.\"",
        "\"He came in _ that round, I though we were gonna lose.\"",
        "\"That car build is so _, nothing can beat it.\"",
        "\"Good game. _.\"",
        "\"Did you see the pictures I posted? The food was _.\"",
        "\"She looks _ for prom this Friday, her hair and makeup is beautiful.\"",
        "\"Why is she being so _, I told her I was sorry.\"",
        "\"That’s my favorite basketball player, he's the _.\"",
        "\"She defintely likes you, _ her up.\"",
        "\"There's a party this weekend, but don’t tell anyone, I want to keep it on the _ _.\"",
        "\"Did you _ just talk to me like that.\"",
        "\"I need gas money.\"\n\"_ _ I got you.\"",
        "\"Can you still make it this weekend?\"\n\"_, Im sorry, something came up.\"",
        "\"Don’t be a _ I told you that already.\"",
        "\"I just finished all my _ work.\""};

    public int[][] answersY = new int[][] { new int[] {0, 1, 2},
        new int[] {0, 1, 2}};
}
