using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Words : MonoBehaviour
{
    public string[] everyoneWords = {"I'm beat.", 
        "a turn off", 
        "couch potato",
        "What's up?",
        "chill",
        "dead (as in a bar or restaurant)",
        "woke",
        "slay",
        "sick",
        "hit the books",
        "I'm game.",
        "nevermind",
        "rad",
        "in the bag",
        "once in a blue moon",
        "You bet.",
        "I don't buy that.",
        "Keep in touch.",
        "I can't even.",
        "No biggie.",
        "No big deal.",
        "No sweat.",
        "show up (someone)",
        "show up for (someone)",
        "have a crush",
        "white-collar",
        "blue-collar",
        "salty",
        "low key",
        "bomb",
        "shady",
        "corny",
        "bummer",
        "jonesing for",
        "sweet",
        "put out",
        "put out",
        "hang out",
        "scared to death",
        "rub it in my face",
        "ship has sailed",
        "have a blast",
        "I'm down",
        "I'm down",
        "rip off",
        "ride shotgun",
        "suck up",
        "have dibs on",
        "fresh meat",
        "pass the buck",
        "go dutch",
        "hit the road",
        "wrap up",
        "are you kidding me?",
        "are you kidding me?!",
        "rain check",
        "all ears",
        "all-nighter",
        "glow up",
        "tune out",
        "ace",
        "nail",
        "screw over",
        "screw up",
        "amped up",
        "spill the beans",
        "dead-ass",
        "have beef",
        "are you down?",
        "are you up to _?",
        "fixin' to",
        "hissy fit",
        "dough",
        "bread",
        "crash (sleep)",
        "lighten up",
        "score",
        "cram",
        "bail",
        "ditch",
        "busted",
        "busted",
        "in no time",
        "freebie",
        "my bad",
        "no worries",
        "I get it",
        "same here",
        "I feel you",
        "epic",
        "hot",
        "cheesy",
        "flaky",
        "dump",
        "break up",
        "party animal",
        "whiz",
        "chicken",
        "chick",
        "I'm in",
        "(be) a blast",
        "pig out",
        "bougie",
        "cool it",
        "drop the ball"};





    public string[] everyoneDefSpanish = {"Estoy agotado.", 
        "algo que no me apetece",
        "haragán, teleadicto",
        "¿Que pasa?",
        "relajarse",
        "nadie está ahí"};

    public string[] everyoneDefEnglish = {"I'm tired, I'm worn out.",
        "unattractive quality",
        "someone who lies on couch/watches TV a lot",
        "How are you?",
        "relax",
        "with few or no people",
        "progressive or left-leaning",
        "to do something spectacularly well",
        "awesome",
        "study",
        "I'm interested in doing that",
        "forget it",
        "awesome",
        "assured of success, virtually won",
        "infrequently",
        "definitely",
        "I don't believe that.",
        "Stay in contact.",
        "I can't believe it.",
        "It's nothing important.",
        "It's nothing important.",
        "It's not hard.",
        "to exceed someone",
        "to help or support someone",
        "to like someone romantically",
        "professional or office",
        "manual or working-class",
        "resentful",
        "simple, discrete",
        "successful, perfect, impeccable",
        "suspicious, dishonest",
        "outdated, silly",
        "dissapointed",
        "strong desire for",
        "awesome, cool",
        "have sexual intimacy with",
        "inconvenienced",
        "spend time together",
        "very afraid",
        "remind me of something unpleasant or superior",
        "it's too late",
        "have fun",
        "I'm available and ready",
        "I'm sad",
        "to overcharge",
        "ride in passenger seat of car",
        "to act nice to win favors",
        "to claim something as yours",
        "recent arrival",
        "to give a job or responsibility to someone else",
        "pay half with another person",
        "to leave",
        "finish up",
        "are you telling the truth?",
        "I don't believe that.",
        "to postpone for another time",
        "listening",
        "to stay up all night",
        "remarkable self-improvement",
        "ignore",
        "to get 100%",
        "to do something spectacularly well",
        "to cheat or exploit someone",
        "to make a mistake or do something wrong",
        "excited, ready to go",
        "reveal the truth",
        "truthfully, true",
        "have conflict",
        "are you ready to do something/go somewhere?",
        "do you want to _?",
        "ready to, about to",
        "tantrum",
        "money",
        "money",
        "fall asleep quickly",
        "don't be tense, relax",
        "get something good",
        "study with little time",
        "to leave",
        "to leave someone",
        "broken, ruined",
        "to catch, arrest",
        "quickly",
        "something free (no cost)",
        "my fault",
        "don't stress",
        "I understand",
        "I feel the same",
        "I understand, I feel the same",
        "amazing, grand",
        "attractive ",
        "embarrassing, trying too hard",
        "unreliable, late",
        "end a relationship with",
        "end a relationship with",
        "someone who loves parties",
        "genius, someone competent and fast",
        "coward",
        "girl, woman",
        "I'm ready, I will join",
        "(be) very fun",
        "eat too much",
        "luxury, expensive",
        "calm down",
        "to fail at something, leave a job for someone else"};

    public string[] everyoneExample = {"I had such a long day. I'm beat.",
        "Nail biting is a real turn off for me.",
        "Have you been watching TV all day? You're such a couch potato.",
        "Long time. What's up?",
        "I just got home from work. I need to chill.",
        "This club is dead. Let's go somewhere else."};


    public string[] youngWords = {"cringe",
        "simp",
        "lit"};
    public string[] youngDefinition = {"tener vergüenza ajena",
        "una persona que se esfuerza en exceso en impresionar a alguien que le gusta",
        "chingón"};
    public string[] youngExample = {"You sleep with a teddy bear? Cringe.",
        "Don't pick up food for her everytime she asks. She's going to think you're a simp.",
        "This party is lit."};
    
}
