using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Words : MonoBehaviour
{
    public string[] everyoneWords = {"I'm beat.", 
        "a turn off", 
        "couch potato",
        "What's up?",
        "chill",
        "dead (as in a bar or restaurant)",
        "woke",
        "slay",
        "sick",
        "hit the books",
        "I'm game.",
        "nevermind",
        "rad",
        "in the bag",
        "once in a blue moon",
        "You bet.",
        "I don't buy that.",
        "Keep in touch.",
        "I can't even.",
        "No biggie.",
        "No big deal.",
        "No sweat.",
        "show up (someone)",
        "show up for (someone)",
        "have a crush",
        "white-collar",
        "blue-collar",
        "salty",
        "low key",
        "bomb",
        "shady",
        "corny",
        "bummer",
        "jonesing for",
        "sweet",
        "put out",
        "put out",
        "hang out",
        "scared to death",
        "rub it in my face",
        "ship has sailed",
        "have a blast",
        "I'm down",
        "I'm down",
        "rip off",
        "ride shotgun",
        "suck up",
        "have dibs on",
        "fresh meat",
        "pass the buck",
        "go dutch",
        "hit the road",
        "wrap up",
        "are you kidding me?",
        "are you kidding me?!",
        "rain check",
        "all ears",
        "all-nighter",
        "glow up",
        "tune out",
        "ace",
        "nail",
        "screw over",
        "screw up",
        "amped up",
        "spill the beans",
        "dead-ass",
        "have beef",
        "are you down?",
        "are you up to _?",
        "fixin' to",
        "hissy fit",
        "dough",
        "bread",
        "crash (sleep)",
        "lighten up",
        "score",
        "cram",
        "bail",
        "ditch",
        "busted",
        "busted",
        "in no time",
        "freebie",
        "my bad",
        "no worries",
        "I get it",
        "same here",
        "I feel you",
        "epic",
        "hot",
        "cheesy",
        "flaky",
        "dump",
        "break up",
        "party animal",
        "whiz",
        "chicken",
        "chick",
        "I'm in",
        "(be) a blast",
        "pig out",
        "bougie",
        "cool it",
        "drop the ball"};





    public string[] everyoneDefSpanish = {"estoy agotado, ando muerto",
        "algo que me quita las ganas",
        "haragán, teleadicto",
        "¿Qué onda?, ¿Qué tal?",
        "relajarse",
        "está vacio",
        "progresista, de izquierda",
        "arrasar, devorar",
        "chingón",
        "estudiar",
        "le entro, me apunto",
        "no pasa nada, olvídalo",
        "padrísimo",
        "es un hecho, de ley, en la bolsa",
        "casi nunca, cada luna azul",
        "¡por supuesto!",
        "No manches.",
        "Nos seguimos viendo.",
        "No puedo creerlo.",
        "No es gran cosa. No es para tanto.",
        "No es gran cosa. No es para tanto.",
        "No es gran cosa. No es para tanto.",
        "exponer, superar",
        "hecharle porras, apoyar, dar apoyo",
        "estar enamorado, me gusta alguien",
        "asalariado, godín, oficinista",
        "trabajador manual, obrero",
        "resentido, sentido, ofendido",
        "discreto, sencillo, simple",
        "exitoso, perfecto, impecable",
        "sospechoso, deshonesto, chueco, turbio",
        "cursi",
        "que mala onda",
        "tener antojo intenso de, traer antojo de",
        "chido",
        "acostarse con alguien",
        "molestar, incomodar",
        "pasar el rato",
        "muerto de miedo",
        "restregar en la cara",
        "ya es muy tarde",
        "divertirse, pasarla chido",
        "jalo",
        "ando triste, ando depre",
        "estafar, hacer güey",
        "ir de copiloto, ir en frente",
        "lamer botas, lambisconear",
        "pedirse, me toca",
        "carne fresca, recién llegado",
        "cargarle el muerto a alguien,\necharle el problema a alguien",
        "pagar la mitad",
        "irse",
        "terminar, concluir",
        "¿Me estás tomando el pelo?, ¿estas bromeando?",
        "¡No es cierto!, ¡No te creo!",
        "En otra ocasión, reagendar",
        "soy todo oídos",
        "algo que dura toda la noche",
        "renovacion total, cambio radical",
        "ignorar",
        "sacar un 100%",
        "te la rifaste",
        "joder a alguien, chingar a alguien",
        "regarla, cagarla, meter la pata",
        "con toda la energia, emocionado, entusiasmado",
        "soltar la sopa, contar el chisme",
        "neta, te lo juro",
        "tener bronca",
        "¿jalas?, ¿le entras?, ¿vienes?",
        "¿jalas a?, ¿le entras a?, ¿quieres?",
        "voy a, apunto de",
        "berrinche",
        "lana",
        "lana",
        "caer como piedra, dormir rapidamente",
        "relajarse, calmarse",
        "afortunadamente conseguir",
        "estudiar a ultima hora",
        "irse, fuga",
        "abandonar, dejar",
        "roto, no sirve",
        "atrapado",
        "en poco tiempo, rapidamente",
        "algo gratis",
        "mala mía",
        "no te apures, no te preocupes",
        "lo entiendo, te entiendo",
        "igual",
        "te entiendo",
        "épico, genial, colosal",
        "atractivo, estar bueno",
        "cursi",
        "poco confiable, poco fiable",
        "mandar a la chingada",
        "romper, terminar",
        "fiestero, pachanguero, parrandero",
        "genio",
        "gallina",
        "chica, morra, chava",
        "me apunto, le entro, jalo",
        "será/estará genial",
        "comer/tragar como cerdo",
        "fresa",
        "cálmate",
        "meter la pata, regarla"};

    public string[] everyoneDefEnglish = {"I'm tired, I'm worn out.",
        "unattractive quality",
        "someone who lies on couch/watches TV a lot",
        "How are you?",
        "relax",
        "with few or no people",
        "progressive or left-leaning",
        "to do something spectacularly well",
        "awesome",
        "study",
        "I'm interested in doing that",
        "forget it",
        "awesome",
        "assured of success, virtually won",
        "infrequently",
        "definitely",
        "I don't believe that.",
        "Stay in contact.",
        "I can't believe it.",
        "It's nothing important.",
        "It's nothing important.",
        "It's not hard.",
        "to exceed someone",
        "to help or support someone",
        "to like someone romantically",
        "professional or office",
        "manual or working-class",
        "resentful",
        "simple, discrete",
        "successful, perfect, impeccable",
        "suspicious, dishonest",
        "outdated, silly",
        "dissapointed",
        "strong desire for",
        "awesome, cool",
        "have sexual intimacy with",
        "inconvenienced",
        "spend time together",
        "very afraid",
        "remind me of something unpleasant or superior",
        "it's too late",
        "have fun",
        "I'm available and ready",
        "I'm sad",
        "to overcharge",
        "ride in passenger seat of car",
        "to act nice to win favors",
        "to claim something as yours",
        "recent arrival",
        "to give a job or responsibility to someone else",
        "pay half with another person",
        "to leave",
        "finish up",
        "are you telling the truth?",
        "I don't believe that.",
        "to postpone for another time",
        "listening",
        "to stay up all night",
        "remarkable self-improvement",
        "ignore",
        "to get 100%",
        "to do something spectacularly well",
        "to cheat or exploit someone",
        "to make a mistake or do something wrong",
        "excited, ready to go",
        "reveal the truth",
        "truthfully, true",
        "have conflict",
        "are you ready to do something/go somewhere?",
        "do you want to _?",
        "ready to, about to",
        "tantrum",
        "money",
        "money",
        "fall asleep quickly",
        "don't be tense, relax",
        "get something good",
        "study with little time",
        "to leave",
        "to leave someone",
        "broken, ruined",
        "to catch, arrest",
        "quickly",
        "something free (no cost)",
        "my fault",
        "don't stress",
        "I understand",
        "I feel the same",
        "I understand, I feel the same",
        "amazing, grand",
        "attractive ",
        "embarrassing, trying too hard",
        "unreliable, late",
        "end a relationship with",
        "end a relationship with",
        "someone who loves parties",
        "genius, someone competent and fast",
        "coward",
        "girl, woman",
        "I'm ready, I will join",
        "(be) very fun",
        "eat too much",
        "luxury, expensive",
        "calm down",
        "to fail at something, leave a job for someone else"};

    public string[] everyoneDefHindi = {"मैं थक चुका हूँ।",
        "अनाकर्षक गुणवत्ता",
        "टीवी देखकर समय गँवाने वाला",
        "क्या चल रहा है?",
        "शांत हो जाओ",
        "सुना",
        "प्रगतिशील या समाजवादी",
        "शानदार प्रदर्शन करना",
        "अद्भुत, बहुत ही शानदार",
        "पढ़ो",
        "मैं वह करना चाहता हूँ",
        "कोई बात नहीं",
        "बढ़िया",
        "जीत पक्की है",
        "कभी-कभी",
        "बिल्कुल",
        "मैं नहीं मानता/मानती",
        "संपर्क में रहना।",
        "में यकीन नहीं कर सकता/सकती।",
        "यह इतना ज़रूरी नहीं है।",
        "यह कोई बड़ी बात नहीं है।",
        "इसमे कोई परेशानी नहीं है।",
        "किसी को पीछे छोड़ देना, हराना",
        "सहायता करना",
        "किसी को पसंद करना",
        "पेशेवर, कार्यालयी",
        "मजदूर वर्ग",
        "नाराज़, अप्रसन्न",
        "सरल, अलग",
        "सफल, परिपूर्ण, निर्दोष",
        "शंकास्पद, बेईमान",
        "पुराना, उदासीन",
        "निराश",
        "प्रबल इच्छा",
        "प्रशंसनीय, आकर्षक",
        "यौन संबंध बनाना",
        "असुविधा होना",
        "साथ में समय बिताना",
        "बहुत डरा हुआ",
        "मुझे कुछ दुखद या विशेष चीज याद दिलाना",
        "बहुत देर कर दी",
        "मौज करना",
        "मैं तैयार हूँ",
        "मैं दुखी हूँ",
        "अत्यधिक शुल्क लगाना",
        "कार की सहायक सीट पर बेठना",
        "अपने लाभ के लिए किसी से अच्छा व्यवहार करना",
        "किसी चीज पर अपना दावा करना",
        "हाल ही में आए हुए",
        "किसी और को कोई काम या जिम्मेदारी सौंपना",
        "किसी के साथ आधा भुगतान करना",
        "निकाल जाना",
        "खत्म करना",
        "क्या तुम सच बोल रहे हो?",
        "मुझे ऐसा नहीं लगता।",
        "बाद के लिए टाल देना",
        "सुनना",
        "रात भर जागना",
        "अनोखा आत्म-सुधार",
        "नजरंदाज",
        "सौ प्रतिशत प्राप्त करना",
        "कुछ बेहद शानदार तरीके से करना",
        "किसी को बेवकूफ बनाना",
        "कोई गलती/गलत काम करना",
        "उत्सुक, तैयार",
        "सत्य प्रकट करना",
        "सच्चाई से",
        "संघर्ष होना",
        "क्या तुम कुछ करने/कहीं जाने के लिए तैयार हो",
        "क्या तुम ________ करना चाहोगे?",
        "तैयारी है",
        "मनमुटाव",
        "पैसे",
        "दौलत",
        "जल्दी से नींद आ जाना",
        "चिंता मत करो, शांत रहो",
        "कुछ अच्छा पाना",
        "कम समय पढ़ाई करना",
        "छोड़ देना",
        "किसी को छोड़कर चले जाना",
        "टूटा हुआ, नष्ट",
        "पकड़ना, गिरफ्तार",
        "जल्दी",
        "कुछ मुफ़्त",
        "मेरी गलती",
        "फिकर मत करो",
        "मैं समझता/समझती हूँ",
        "मुझे भी यही लगता है",
        "मैं समझ सकता/सकती हूँ",
        "अविश्वसनीय, भव्य",
        "मनमोहक",
        "अजीब, लज्जाजनक",
        "अनिश्चित, देर से",
        "किसी को छोड़ देना",
        "रिश्ता खत्म करना",
        "पार्टी/दावत का शौकीन",
        "ज्ञानी, कुशल और तेज़",
        "कायर, डरपोक",
        "स्त्री, लड़की",
        "मैं आने के लिए तैयार हूँ",
        "मज़ेदार",
        "बहुत ज़्यादा खाना",
        "महंगा, वैभवी",
        "धैर्य रखो",
        "किसी काम में असफल हो जाना, किसी ओर के लिए काम छोड़ देना"};

    public string[] everyoneDefMandarin = {"我很累",
        "让人反感",
        "电视迷",
        "你好吗",
        "轻松悠闲的",
        "几乎没人",
        "革新",
        "把某件事做得很棒",
        "很棒",
        "学习",
        "我觉得很有趣",
        "别介意",
        "很棒",
        "稳操胜券",
        "非常罕见",
        "当然",
        "我不相信",
        "保持联系",
        "我无法相信",
        "没关系",
        "没关系",
        "没有问题",
        "让某人感到尴尬",
        "帮助某人",
        "迷恋某人",
        "白领",
        "蓝领",
        "气愤的",
        "平淡的",
        "成功的；完美的；毫无缺陷的",
        "觉得很可疑",
        "过时的；愚蠢的",
        "让人失望",
        "想要…...",
        "很棒的；很酷",
        "（尤指女性）与某人发生性关系",
        "让某人感到不便",
        "花时间与某人在一起",
        "非常害怕",
        "让某人感到不愉快",
        "太迟了",
        "玩得开心",
        "我已经准备好了",
        "我很难过",
        "以过高的价格出售商品或服务",
        "坐副驾驶座",
        "奉承某人",
        "有权占有某物",
        "新来的人",
        "把责任推卸给别人",
        "各付各的",
        "离开",
        "完成",
        "你没开玩笑吧？",
        "怎么可能？",
        "推迟某事",
        "倾听",
        "通宵",
        "变得更有魅力",
        "忽视",
        "非常优秀",
        "把某事做得非常棒",
        "欺骗或剥削某人",
        "犯错或做错某事",
        "激动的",
        "泄露秘密",
        "的确地",
        "发生冲突",
        "准备好做某事/去哪里了吗?",
        "你想要......吗？",
        "准备…...",
        "发脾气",
        "钱",
        "钱",
        "很快就睡着了",
        "放轻松",
        "得到某个好东西",
        "考试前用很少的时间拼命学习",
        "离开",
        "离开某人",
        "破产",
        "抓住",
        "立刻地",
        "免费的",
        "我的错",
        "别担心",
        "我明白了",
        "我也有同感",
        "我理解/同意你说的",
        "很棒的",
        "吸引人的",
        "尴尬的；过于努力的",
        "不可靠的",
        "结束与……的关系",
        "结束与……的关系",
        "派对狂",
        "奇才；擅长做某事的人",
        "懦夫",
        "女性",
        "我准备好了；我会加入的",
        "很好玩",
        "吃太多",
        "豪华的；昂贵的",
        "冷静下来",
        "失误"};

    public string[] everyoneExample = {"\"I had such a long day. I'm beat.\"",
        "\"Nail biting is a real turn off for me.\"",
        "\"Have you been watching TV all day? You're such a couch potato.\"",
        "\"Long time. What's up?\"",
        "\"I just got home from work. I need to chill.\"",
        "\"This club is dead. Let's go somewhere else.\"",
        "\"That guy is so woke, every weekend he's at another rally.\"",
        "\"Girl you slayed at that interview. No way you're not getting the job.\"",
        "\"That restaurant is sick. They make the best ramen ever.\"",
        "\"I need to hit the books. I have a big exam tomorrow.\"",
        "\"Do you want to go to the grocery store?\"  \"I'm game.\"",
        "\"I hate this restaurant.\" \"What did you say?\" \"Nevermind\"",
        "\"This album is rad. You should listen to it.\"",
        "\"Don't worry about this interview. You've got it in the bag.\"",
        "\"It's once in a blue moon that you love someone this much. Enjoy it.\"",
        "\"Do you want to drive?\" \"You bet.\"",
        "\"You haven't been drinking? I don't buy that.\"",
        "\"I will miss you so much. Please keep in touch.\"",
        "\"She was talking to Brad while Stephanie stood right there? I can't even.\"",
        "\"Is there any way you can you get me some fries too?\" \"No biggie.\"",
        "\"Is there any way you can you get me some fries too?\" \"Sure. No big deal.\"",
        "\"Can you help me with my Physics homework?\" \"No sweat.\"",
        "\"Wow you really showed up Felipe at pool. He barely scored a single point.\"",
        "\"You really showed up for Marge when she got her cancer diagnosis. You are the best friend\"",
        "\"I have a big crush on Eduardo. I can barely look at him in the eyes.\"",
        "\"The Wolf of Wall Street seems like a pretty accurate depiction of wihte-collar crime.\"",
        "\"The unions represent blue-collar workers like farm workers and truck drivers.\"",
        "\"My girlfriend gets salty when she's on her period. She gets mad at me for going out with friends\"",
        "\"Our wedding was pretty low-key. We only invited close friends and family.\"",
        "\"It's a bomb restaurant. You have to try their dumplings.\"",
        "\"That car dealership is pretty shady. I would go somewhere else.\"",
        "\"I liked the movie but the jokes were pretty corny.\"",
        "\"You're going to be out of town on the 10th? Bummer.\"",
        "\"Can we get nachos? I've been jonesing for that fake cheese.\"",
        "\"Hey I got you a ticket for the movie.\"\n\"Sweet\"",
        "\"I never put out on the first date until I met you.\"",
        "\"I feel really put out that you asked me to drive everyone.\"",
        "\"Hey let's hang out this weekend! It's been forever.\"",
        "\"I was scared to death. I coudn't find you anywhere.\"",
        "\"I get that you make a lot of money now but you don't have to rub it in my face.\"",
        "\"I would love to have another child but that ship has sailed.\"",
        "\"Have a blast on your vacation!\"",
        "\"Do you want to try riding ATVs with me?\"\n\"I'm down.\"",
        "\"Hey do you want to go to the movies?\"\n\"No. I'm really down about everything at work. Maybe another time.\"",
        "\"I can't go back to that barbershop. They ripped me off so bad last time. I think I paid double price\"",
        "\"Let me drive. You ride shotgun.\"",
        "\"She always sucks up to her professors. That's how she gets good grades.\"",
        "\"I have dibs on the chocolate ice cream. You can eat the vanilla.\"",
        "\"Ah the freshmen have arrived. Fresh meat.\"",
        "\"I want to pass the buck so you can play your song but I'm having so much fun playing this ukelele.\"",
        "\"Can we go dutch for dinner? It seems fair.\" ",
        "\"Let's hit the road. If we're going to get there by dark we need to head out now.\"",
        "\"I just need to wrap up a few things at work and I'll be home.\"",
        "\"Wait. You said Abigail is at the house. Are you kidding me?\"",
        "\"Wait. You already cleaned your room? Are you kidding me?!\"",
        "\"It turns out I can't make the lunch today. Can I take a rain check?\"",
        "\"Are you even listening?\"\n\"As soon as you started talking about lunch I was all ears.\"",
        "\"Have you finished your essay yet.\"\n\"Nope. I'm just going to drink coffee and pull an all-nighter. I'll get it done.\"",
        "\"Look at his photo. That boy had a real glow up. I've never seen him look so good.\"",
        "\"I brought earbuds on the plane so I could tune out everything but my audiobook.\"",
        "\"How did you do on the exam?\"\n\"Who, me? Aced it.\"",
        "\"Wow this cake is really delicious. What is the recipe? You nailed it.\"",
        "\"I'm not going to let another mechanic screw me over. I can take my car somewhere else.\"",
        "\"I am so sorry I screwed up the car. I was trying to figure out how to adjust the A/C but I think I pushed too many buttons.\"",
        "\"I'm really amped up for the concert tonight. I may have drunk too much coffee.\"",
        "\"How did your date go? Spill the beans.\"",
        "\"Wait you only have $10 in your account?\"\n\"Dead-ass.\"",
        "\"I know we don't always agree but I'm tired of having a beef with you all the time.\"",
        "\"I need to go to the mall to pick up some shoes at 11. Are you down to join?\"",
        "\"I need to go to the mall to pick up some shoes at 11. Are you up to coming along?\"",
        "\"I'm fixin' to head out now if you want to come.\"",
        "\"Samantha had a hissy fit in the store when I said I wouldn't buy her ice cream.\"",
        "\"I don't have enough dough for Taylor Swift tickets. You can go without me.\"",
        "\"I don't have enough bread for Taylor Swift tickets. You can go without me.\"",
        "\"I barely slept all night. If we put on a movie, I think I'll crash.\"",
        "\"Lighten up. The final is only worth 10% of your grade in the class.\"",
        "\"I scored 2 tickets to the game if you want to come!\"",
        "\"I have to cram for my biology exam. I am so behind in this class.\"",
        "\"I love you but I have to bail. I told Teresa I would meet her for coffee.\"",
        "\"Please don't ditch me at the party. I don't know anyone.\"",
        "\"My phone is completely busted. I really need to get a new one.\"",
        "\"I busted Michael trying to leave early. Why does he hate parties so much?\"",
        "\"I'm sorry I'm running late but I'll be there in no time.\"",
        "\"I heard they are giving freebie frozen yogurts coupons to the first 50 shoppers.\"",
        "\"You stepped on my foot.\"\n\"Sorry. My bad.\"",
        "\"We're going to be late to the movie.\"\n\"No worries. The first 20 minutes are trailers anyway.\"",
        "\"I feel like I'm never good enough\"\n\"I get it. It's hard to go to college and get a degree.\"",
        "\"I'm struggling so much to understand the professor.\"\n\"Same here. This is a hard class.\"",
        "\"The A/C is on way too high in this office. I'm freezing.\"\n\"I feel you.\"",
        "\"Wow that was epic. I love going sailing now.\"",
        "\"You look so hot in that dress.\"",
        "\"I don't like romantic comedies. They're too cheesy for me.\"",
        "\"You were supposed to be here an hour ago. You're so flaky.\"",
        "\"I think John is having an affair.\"\n\"You need to dump him.\"",
        "\"I need to break up with Natasha. I just don't feel like she supports me.\"",
        "\"I used to be a party animal, but now I go to bed at 11 pm without fail.\"",
        "\"David is a whiz with a electronics. Maybe he can fix it.\"",
        "\"I would try the zip line, but honestly I'm a chicken.\"",
        "\"I met this chick yesterday who said she gives $40 massages.\"",
        "\"Do you want to go rollarskating with me?\"\n\"I'm in.\"",
        "\"I'm going the beach this weekend. You should come. It will be a blast.\"",
        "\"I'm starving. I'm gonna pig out so bad when we get to the restaurant.\"",
        "\"Drinking at Starbucks is a little bougie for me. I prefer to make my own coffee\"",
        "\"I need you to cool it. Fighting with him won't help anything.\"",
        "\"I don't want to drop the ball on this assignment, but I'm running out of time. I need your help.\""};


    public string[] youngWords = {"cringe",
        "simp",
        "lit",
        "lit",
        "swole",
        "drip",
        "finna",
        "Bet.",
        "dope",
        "low key",
        "gucci",
        "shook",
        "sus",
        "whip",
        "on fleek",
        "ghost",
        "yas",
        "no cap",
        "on point",
        "mad (as in very)",
        "stupid (as in very)",
        "slaps",
        "bussin",
        "tats",
        "mid",
        "clutch",
        "OP",
        "W",
        "dank",
        "snatched",
        "extra",
        "GOAT",
        "rizz",
        "down-low",
        "deadass",
        "say less",
        "nah",
        "dumbass",
        "stupid-ass"};

    public string[] youngDefEnglish = {"embarrassing",
        "someone who tries too hard to please their romantic partner or crush",
        "really great, fantastic",
        "drunk, high",
        "muscular",
        "fashionable clothes, style",
        "going to, about to",
        "definitely",
        "awesome",
        "secretly",
        "fancy, fashionable, great",
        "surprised",
        "suspicious",
        "luxury car",
        "excellent, perfectly done",
        "disappear, block on social media",
        "yes with emphasis",
        "no lie",
        "perfectly done, appropriate",
        "very, so",
        "very, so",
        "really great, fantastic",
        "delicious",
        "tattoos",
        "mediocre",
        "done in the last minute to convert a loss to a win",
        "overpowered",
        "a win",
        "high quality",
        "attractive, amazingly good",
        "trying too hard, dramatic",
        "greatest of all time",
        "charisma to attract romantic partners",
        "secretly, with discretion",
        "seriously",
        "I understand, ok",
        "no",
        "stupid person",
        "dumb"};

    public string[] youngDefSpanish = {"vergonzoso, avergonsarze,\n tener vergüenza ajena",
        "enamorado a ciegas",
        "chingón",
        "borracho, drogado",
        "musculoso, mamado",
        "estilo, ropa con estilo",
        "voy a, apunto de",
        "¡por supuesto!, a huevo",
        "chingón",
        "en secreto, a escondidas",
        "de moda, lujoso",
        "en shock, pasmado, con el ojo cuadrado",
        "sospechoso",
        "coche de lujo",
        "en su punto, perfectos",
        "ghostear, desaparecer",
        "sí con enfasis, eso",
        "fuera de broma, fuera de pedo",
        "en el clavo",
        "muy, tan",
        "muy, tan, estupidamente",
        "chingón, chido",
        "sabroso, buenisimo",
        "tatuajes, tatus",
        "mediocre",
        "la salvaste, salvarla",
        "OP, demasiado poderoso",
        "una victoria",
        "alta calidad",
        "chingón, chido",
        "extra, dramatico",
        "el/la mejor de todos los tiempos",
        "pegue, carisma",
        "en secreto, a escondidas",
        "en serio, neta",
        "no se diga mas",
        "no, nel",
        "estúpido, imbécil, pendejo",
        "estúpido, imbécil, pendejo"};

    public string[] youngDefHindi = {
        "शर्मिंदा करने वाला",
        "बेहद चाहने वाला",
        "शानदार",
        "नशे में धुत्त",
        "रुष्ट पुष्ट, मांसल",
        "नए और सुंदर कपड़े",
        "करने वाला हूँ, करने वाला है",
        "बेशक",
        "अद्भुत",
        "शांति से, गुप्त रूप से",
        "सुंदर, शानदार",
        "चौंका हुआ",
        "संदिग्ध",
        "आलीशान गाड़ी",
        "उत्तम, सही तरीके से किया गया",
        "गायब हो जाना, सोशल मीडिया पर अवरुद्ध करना",
        "हाँ बिल्कुल",
        "यकीन मानो",
        "पूरी तरह से किया गया, उपयुक्त",
        "बहुत",
        "बेवकूफ",
        "बढ़िया",
        "स्वादिष्ट",
        "गोदना",
        "औसत दर्जे का",
        "अंतिम समय में हार को जीत में बदलना",
        "शक्ति से प्रभावित करना",
        "जीत",
        "उच्च गुणवत्ता",
        "आकर्षक",
        "बहुत कोशिश करना, नाटकीय",
        "अब तक का सर्वश्रेष्ठ",
        "प्रेमी-प्रेमीका को आकर्षित करने वाला आकर्षण",
        "गुप्त रूप से",
        "गंभीरता से",
        "ठीक है, मैं समझ गया",
        "नहीं",
        "मूर्ख व्यक्ति",
        "अज्ञानी"};


    public string[] youngDefMandarin = {"尴尬的",
        "舔狗",
        "太棒了",
        "喝醉了",
        "健壮的",
        "时髦的",
        "要做某事",
        "当然",
        "很棒",
        "偷偷地",
        "很酷；时髦",
        "惊讶的",
        "觉得很可疑",
        "豪华汽车",
        "很棒；完美",
        "失联；在社交媒体上消失",
        "没错",
        "不撒谎",
        "非常棒",
        "非常地",
        "非常地",
        "很棒",
        "（常指食物）非常棒",
        "刺身",
        "中等的",
        "在紧急时刻发挥重要作用",
        "强大的",
        "胜利",
        "高质量的",
        "有吸引力的；非常棒",
        "过度的；戏剧化的",
        "史上最佳",
        "吸引人的",
        "偷偷地",
        "的确地",
        "知道了",
        "不",
        "笨蛋",
        "愚蠢"};

    public string[] youngExample = {"\"You sleep with a teddy bear? Cringe.\"",
        "\"Don't pick up food for her everytime she asks. She's going to think you're a simp.\"",
        "\"This party is lit.\"",
        "\"I'm going to get lit at this party.\"",
        "\"Have you been working out? You look swole, bro.\"",
        "\"Nike shoes and a Nike jacket? I like your drip.\"",
        "\"I'm finna go to the mall.\"",
        "\"Do you want to drive?\" \"Bet.\"",
        "\"Your shoes are dope. Did you get them in L.A.?\"",
        "\"I'm low key obsessed with Nicki Minaj.\"",
        "\"My sister is so gucci. She said she will pay for everyone.\"",
        "\"I'm a little shook you just said you are going to leave.\"",
        "\"That guy looks sus. Can we go somewhere else?\"",
        "\"Check out this whip. It's only $60K.\"",
        "\"That dress is on fleek. He's going to love it.\"",
        "\"We had a couple of dates. We were texting everyday. Then she ghosted me. I don't know what went wrong\"",
        "\"You want to come with me to the DMV? Yas!\"",
        "\"I love to eat wheatgrass. No cap. I think it tastes good.\"",
        "\"Wearing sandals is really on point. I didn't know it would be this hot today.\"",
        "\"That restaurant is mad cheap.\"",
        "\"Wow you did stupid good on that exam. I should study with you next time.\"",
        "\"That taco shop is ok but their salsa slaps.\"",
        "\"Have you tried the dumplings? They're bussin\"",
        "\"He has tats all over his arms. One looks like a snake wrapping around him.\"",
        "\"The food is pretty mid at that taco shop. I know a better spot.\"",
        "\"In a clutch move, the team scored for the win in the final seconds of the game.\"",
        "\"That player is OP. When they're in the game, you've already lost.\"",
        "\"Nice game, bro. W.\"",
        "\"Your sneakers are really dank.\"",
        "\"You look snatched in that dress!\"",
        "\"Six inch heels might be a little extra for a Thanksgiving dinner.\"",
        "\"Michael Jorden was the GOAT of basketball. Prove me wrong.\"",
        "\"Bryce has so much rizz. He got a girl's phone number at the movies while the movie was playing.\"",
        "\"Keep this on the down-low, but I'm thinking about quitting this job.\"",
        "\"Did she actually say that out loud to him?\"\n\"Deadass.\"",
        "\"Bryan, you need to start your homework now.\"\n\"Say less, mom. I got it.\"",
        "\"Are you going to the beach this weekend?\"\n\"Nah. I already got plans with Kate.\"",
        "\"I love you, but sometimes you're such a dumbass.\"",
        "\"If I hear another stupid-ass thing come out of your mouth, I will scream.\""};
    
}
