using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Words : MonoBehaviour
{
    public string[] everyoneWords = {"I'm beat.", 
        "a turn off", 
        "couch potato",
        "What's up?",
        "chill",
        "dead (as in a bar or restaurant)",
        "woke",
        "slay",
        "sick",
        "hit the books",
        "I'm game.",
        "nevermind",
        "rad",
        "in the bag",
        "once in a blue moon",
        "You bet.",
        "I don't buy that.",
        "Keep in touch.",
        "I can't even.",
        "No biggie.",
        "No big deal.",
        "No sweat.",
        "show up (someone)",
        "show up for (someone)",
        "have a crush",
        "white-collar",
        "blue-collar",
        "salty",
        "low key",
        "bomb",
        "shady",
        "corny",
        "bummer",
        "jonesing for",
        "sweet",
        "put out",
        "put out",
        "hang out",
        "scared to death",
        "rub it in my face",
        "ship has sailed",
        "have a blast",
        "I'm down",
        "I'm down",
        "rip off",
        "ride shotgun",
        "suck up",
        "have dibs on",
        "fresh meat",
        "pass the buck",
        "go dutch",
        "hit the road",
        "wrap up",
        "are you kidding me?",
        "are you kidding me?!",
        "rain check",
        "all ears",
        "all-nighter",
        "glow up",
        "tune out",
        "ace",
        "nail",
        "screw over",
        "screw up",
        "amped up",
        "spill the beans",
        "dead-ass",
        "have beef",
        "are you down?",
        "are you up to _?",
        "fixin' to",
        "hissy fit",
        "dough",
        "bread",
        "crash (sleep)",
        "lighten up",
        "score",
        "cram",
        "bail",
        "ditch",
        "busted",
        "busted",
        "in no time",
        "freebie",
        "my bad",
        "no worries",
        "I get it",
        "same here",
        "I feel you",
        "epic",
        "hot",
        "cheesy",
        "flaky",
        "dump",
        "break up",
        "party animal",
        "whiz",
        "chicken",
        "chick",
        "I'm in",
        "(be) a blast",
        "pig out",
        "bougie",
        "cool it",
        "drop the ball"};





    public string[] everyoneDefinition = {"Estoy agotado.", 
        "algo que no me apetece",
        "haragán, teleadicto",
        "¿Que pasa?",
        "relajarse",
        "nadie está ahí"};

    public string[] everyoneExample = {"I had such a long day. I'm beat.",
        "Nail biting is a real turn off for me.",
        "Have you been watching TV all day? You're such a couch potato.",
        "Long time. What's up?",
        "I just got home from work. I need to chill.",
        "This club is dead. Let's go somewhere else."};


    public string[] youngWords = {"cringe",
        "simp",
        "lit"};
    public string[] youngDefinition = {"tener vergüenza ajena",
        "una persona que se esfuerza en exceso en impresionar a alguien que le gusta",
        "chingón"};
    public string[] youngExample = {"You sleep with a teddy bear? Cringe.",
        "Don't pick up food for her everytime she asks. She's going to think you're a simp.",
        "This party is lit."};
    
}
